### ISSUE TITLE
can the graphite version be updated again?

### ISSUE THREAD

**Issue by schen2315** [raintank/graphite-mt#41]
Hello, i see the current version of graphite is ~9 months old `GRAPHITE_VERSION=7ebde4c60` . Can the graphite version be updated to the latest version again? There are some recent changes we would like to get.

**Comment by replay** [comment]
definitely, that was on my list of things to do and I'll get to it soon

**Comment by schen2315** [comment]
hello, is there any timeline for this?

**Comment by Dieterbe** [comment]
Hi, we have just pushed new images to https://hub.docker.com/r/raintank/graphite-mt/tags
the last one at this time is 9-cc00aa18ae-rebase-v2
