### ISSUE TITLE
Repo is not publishing latest image

### ISSUE THREAD

**Issue by tehlers320** [raintank/graphite-mt#8]
The image on dockerhub is 8 months old.

**Comment by Dieterbe** [comment]
yeah, we haven't set up any CI/CD yet. for now, it's a manual process.

**Comment by Dieterbe** [comment]
Hi Tim, we have just pushed new images to https://hub.docker.com/r/raintank/graphite-mt/tags
the last one at this time is 9-cc00aa18ae-rebase-v2
